version: '3'

services:

  postgres:
    image: postgres:16
    container_name: postgres_db
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
#      - ./postgres_data:/var/lib/postgresql/data
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_db
    ports:
      - "${CLICKHOUSE_NATIVE_PORT}:9000"
      - "${CLICKHOUSE_HTTP_PORT}:8123"
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DATABASE: ${CLICKHOUSE_DB}
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    restart: unless-stopped

  metabase:
    image: metabase/metabase:latest
    container_name: metabase_app
    ports:
      - "${METABASE_PORT}:3000"
    environment:
      MB_DB_TYPE: h2
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - ./metabase_data:/metabase-data
      - ./metabase-drivers:/plugins  # Для кастомных драйверов (clickhouse)

    restart: unless-stopped

  airflow-webserver:
    image: apache/airflow:2.9.3
    container_name: airflow-webserver
    command: webserver
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW_UID=50000
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - airflow_data:/opt/airflow
    restart: always

  airflow-scheduler:
    image: apache/airflow:2.9.3
    container_name: airflow-scheduler
    command: scheduler
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW_UID=50000
    env_file:
      - .env
    depends_on:
      - airflow-webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - airflow_data:/opt/airflow
      - ./airflow_init.sh:/opt/airflow/airflow_init.sh
    entrypoint: ["/bin/bash", "/opt/airflow/airflow_init.sh"]
    restart: always

volumes:
  clickhouse_data:
  postgres_data:
  airflow_data:
